version: "3.9"

services:

  flask:
    build: flask/.
    restart: always
    env_file:
      - ./.env
    deploy:
      replicas: 3

  nginx:
    build: nginx/.
    ports:
      - 80:8080
    depends_on:
     - flask
    restart: always    
